### ISSUE TITLE
How can i add my own attribute?

### ISSUE THREAD

**Issue by dronov-dmitry** [Moult/blender-bim-ifc#1]
I can add only 6 attributes
![изображение](https://user-images.githubusercontent.com/9892891/71771034-9ce53900-2f3d-11ea-8792-a6f1ed0e81d6.png)
how can i add my own attributes
for example the Mass

**Comment by Moult** [comment]
Closing this repo. Please use https://github.com/IfcOpenShell/IfcOpenShell/issues/749#event-2922027120 instead
